defaults:
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ./outputs/${run_id}
  job_logging:
    handlers:
      file:
        filename: ${hydra.run.dir}/log.log

batch_size: 100
chat_template:
  - ''
  - ''
use_binary_search: true
data_idx:
dataset:
discrete_optimizer: gcg
experiment_name: ${model_name}_${discrete_optimizer}_${lr}_${batch_size}_${num_steps}_${topk}_${seed}
input_str: ''
lr: 0.01
max_tokens: -1
mini_batch_size: 100
model_name: EleutherAI/pythia-410m
num_steps: 200
optimizer: adam
random_weights: false
run_id: ${generate_id:}
seed: 42
system_prompt: ''
target_str: jumps over the lazy dog
topk: 250

